### ISSUE TITLE
Windows OS Confusion to use and contribute

### ISSUE THREAD

**Issue by gozeloglu** [hyperledger-labs/minifabric#114]
Hi @litong01 Firstly, thank you for this tool. I have a couple of questions about minifabric. I am going to use this tool my senior project. We are going to develop a tool which automates the installation process of the blockchain tools like Hyper-ledger. Minifabric is a good reference for us to start the project. We are going to extend minifabric features with adding new functionalities. I am not sure that we are going to develop with contributing the this repository or whether forking that repo and develop on our new forked repo. My questions as follow:

1.  I watched the first video of your video series and you said https://youtu.be/QCsKQ1S4C9E?t=278 here minimum requirements are **Linux or OS X**. I am using Windows 10. As I said above I want to add new functionalities to this tool. So, can I add new functionalities to this tool on the Windows machine? I cannot buy a new MacBook or install Linux distribution due to the technical problems with my computer. Also, I do not have enough memory or storage on my computer. So, is it possible to develop and make a contribution to this project on a Windows machine? 

2.  I read the LICENCE and I understood that we can fork and develop on our repository without making contributions to the main project, right?

That's all my questions. Thanks in advance. Just let me know if there will be something that I can help and contribute.

**Comment by litong01** [comment]
@gozeloglu this is open source project, you can fork and copy and do whatever you need to, not an issue. As the current readme.md says, it now supports LInux, OS X and Windows 10. You only need to have docker available on your windows 10 machine to work with it. not a problem at all. If you like to add new functions to it and these new functions are useful, you are welcome to contribute back, but that is totally up to you. Since this is really a question, not an issue to Minifabric, please ask your questions in rocket.chat #fabric-mini. and also please close this issue.
