### ISSUE TITLE
Hyperledger Explorer shows only a part of the network

### ISSUE THREAD

**Issue by togugg** [hyperledger-labs/minifabric#115]
Hi All,

with a fresh minifabric download and standard config, I run the following command:
`minifab netup,create,join,profilegen -e false`

Then I start the Hyperledger Explorer via minifabric:
`minifab explorerup`

The explorer starts all fine. However, it only shows the peers of org0 and the orderers.

With external endpoints exposed the behavior changes:
`minifab netup,create,join,profilegen -e true`

Now the Explorer only shows the first peer of org0. The second peer and the orderers are not shown anymore.
I can confirm that otherwise, the network runs fine. I can install a chaincode and use it via node.js client.

Can I start the Hyperledger Explorer to show the entire network?

Thanks in advance!

**Comment by litong01** [comment]
This is due to explorer limitation. Explorer uses ip address to identify nodes, when you have -e true, all nodes have same ip, thus explorer shows one ip only. If you use -e false or not to use that flag at all, explorer should show all nodes with node name. Please try that, I have also talked to explorer team about this but they have not had a fix for it.

**Comment by litong01** [comment]
@togugg did you try ? If it is like what I described, then please close this as it is not an issue of minifabric. Otherwise, please post your configuration and command you run to reproduce it.

**Comment by togugg** [comment]
@litong01 Thank you very much for your quick response.

With `./minifab up` (and EXPOSE_ENDPOINTS=false) everything works fine.

I will close the issue.

Keep up the great work!
