### ISSUE TITLE
Set arbitrary ip address

### ISSUE THREAD

**Issue by jmfrancofraiz** [hyperledger-labs/minifabric#166]
It'd be nice if you could set an arbitrary ip address, instead of detecting it, as sometimes the detected address doesn't neccesarily have to be the address to be used from another LAN.

In order to do so, I suggest changing minifab script this this little enhancement, so ADDRS can be set thru an env var:

```
#!/bin/bash
[ ! -d "$(pwd)/vars" ] && mkdir vars
if [ -n "${IP_ADDRESS}" ]; then
  ADDRS=${IP_ADDRESS}
elif type ip > /dev/null 2>&1; then
  ADDRS=$(ip addr|grep 'inet '|grep -v '\.1/'|tr -s ' '|awk '{$1=$1};1'|cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -|sed s/addr://g)
else
  ADDRS=$(ifconfig|grep 'inet '|grep -v '\.1 '|tr -s ' '|awk '{$1=$1};1'|cut -d ' ' -f 2|cut -d '/' -f 1|paste -sd "," -|sed s/addr://g)
fi

if [ -f "$(pwd)/spec.yaml" ]; then
  echo "Using spec file: $(pwd)/spec.yaml"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -v $(pwd)/spec.yaml:/home/spec.yaml -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
else
  echo "Using default spec file"
  docker run --rm --name minifab -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/vars:/home/vars \
  -e "ADDRS=$ADDRS" hyperledgerlabs/minifab:latest /home/main.sh "$@"
fi
```

**Comment by litong01** [comment]
Use endpoint in spec.yaml file to do that. Please close this issue.

**Comment by RatakondalaArun** [comment]
Which env variable to set

**Comment by davidkhala** [comment]
@RatakondalaArun This is not a question to MiniFabric, but Docker. Please learn the Docker networks knowledger instead.

**Comment by RatakondalaArun** [comment]
@davidkhala  
After restarting my machine I am unable to install chaincode on fabric network

![image](https://user-images.githubusercontent.com/47482264/113733633-46564400-9718-11eb-8031-41afc4e344bb.png)

This was my host address before restart `169.254.18.30:7004`

now it is changed to `169.254.101.31`

If you notice the error It is trying to connect to my old address
![image](https://user-images.githubusercontent.com/47482264/113733919-83223b00-9718-11eb-8d08-df37e5772679.png)

Now I am asking is there a way to manually set `hostaddress` instead of picking it from my network in minifabric

**Comment by davidkhala** [comment]
@RatakondalaArun It is not an IP issue, You should run `minifab cleanup` after accidental restart while before you boostrap new fabric network. 
@litong01 Correct me if I am wrong.

**Comment by RatakondalaArun** [comment]
> Use endpoint in spec.yaml file to do that. Please close this issue.

@davidkhala here it was said that we can set that endpoint  manually through spec.yaml

**Comment by litong01** [comment]
@RatakondalaArun ip address gets used when generate certificate so that your fabric network wont complain that your certs are not valid. When your machine keeps changing its IP, it is a bit difficult. Unless you are using domain names to generate the certificate. If your environment is a production environment, you can not really use an IP address to do that, I would strongly suggest that you use a real domain name, if this is not a production env, you should do cleanup and set it up again.

**Comment by RatakondalaArun** [comment]
Thank you for the reply I will clean up and rebuild
