### ISSUE TITLE
Error in ChainCode (Java Script) Installation

### ISSUE THREAD

**Issue by NaViGatorFL** [hyperledger-labs/minifabric#172]
Hi,

I developed chain code in Hyperleder Fabric VS code extension using Typescript and Compiled to get a Javascript file.
I copied two files package.json and my-asset-contract.js file and copied them into a folder under the new folder created called asset in the directory /vars/chaincode/node/asset as suggested in the documentation. Now I run the channel code installation command
./minifab -sudo install -n asset -v 1.0 as suggested in documentation and youtube tutorial but It fails to install.

I have enclosed the error of screenshot. I was wondering why the error points out that minifabric is looking for go counterpart of file. How to install my smart contract which is designed in Javascript and developed in VS Code Extension for Fabric
![image](https://user-images.githubusercontent.com/33550840/109588987-9ddd1080-7ad7-11eb-9a5a-d5f3906a89be.png)

**Comment by litong01** [comment]
@NaViGatorFL you have at least two issues (please read the docs), you said that you are using javascript, but you did not specify that in your command, (use -l to specify). also your chaincode should have been in vars/chaincode/asset/node directory, you got it backwards.

**Comment by NaViGatorFL** [comment]
> @NaViGatorFL you have at least two issues (please read the docs), you said that you are using javascript, but you did not specify that in your command, (use -l to specify). also your chaincode should have been in vars/chaincode/asset/node directory, you got it backwards.

Thanks, @litong01 for the response.
For issue 1, it's my bad. It was a typo in reporting. Actually, my smart contract is stored in vars/chaincode/asset/node directory only.
For issue 2, I didn't see this command -l in the documentation https://github.com/hyperledger-labs/minifabric/tree/main/docs#install-your-own-chaincode

Anyways, I tried that command. It is looking for 'asset__1.0.tar.gz' file, how to get or package such chain code file?


![image](https://user-images.githubusercontent.com/33550840/109644260-406eb100-7b23-11eb-8d7d-c2dd9c1390a0.png)

**Comment by litong01** [comment]
Simply run minifab without any parameter, you will see all available commands and parameters.

**Comment by NaViGatorFL** [comment]
Thanks! @litong01 

Folks!

I'm stuck at **initialize** step. It's not moving further. I checked all source code files of the smart contract. Basically, I developed a smart contract in VS Code Extension of Fabric and trying to deploy it here. I tried tearing down and up the network again, as suggested by some people on stackexchange.

Please suggest what went wrong.

![image](https://user-images.githubusercontent.com/33550840/109735019-fa9c0200-7b8f-11eb-82a0-31d0dac75837.png)

**Comment by litong01** [comment]
It seems to me that you are not passing right initializing parameters to your own chaincode, from the error I can see you are still using the default parameter for simple chaincode. I am pretty sure your chaincode won't take the same initializing parameter as the simple chaincode. Be aware that approve,commit and initialize have to use the same parameters to be successful. Also please look at the docs on how chaincode parameters work and how to pass parameters for chaincode in minifabric. Please close this issue after you use right parameters for approve, commit and initialize.

**Comment by pkirkinezis** [comment]
> 
> 
> Thanks! @litong01
> 
> Folks!
> 
> I'm stuck at **initialize** step. It's not moving further. I checked all source code files of the smart contract. Basically, I developed a smart contract in VS Code Extension of Fabric and trying to deploy it here. I tried tearing down and up the network again, as suggested by some people on stackexchange.
> 
> Please suggest what went wrong.
> 
> ![image](https://user-images.githubusercontent.com/33550840/109735019-fa9c0200-7b8f-11eb-82a0-31d0dac75837.png)

Yeah . Its a common issue .
You have to check a few solutions .But first tell us 

1. What your init function is doing ?
2. Does the ledger have any old data from previous version of chaincode ?

Because as @litong01  this indicates error in your init function and ferther more maybe the key data your init functions tries to retrieve or set .

**Comment by litong01** [comment]
From the image, I can see that you never changed the parameters for your
initialize operation, the default parameters still show in the context. I
do not know anything about your asset chaincode but the chance that the
initialization parameters are exactly same as the simple chaincode which
comes with minifabric is very low. Also remember that if your chaincode
requires initialization, then the approve method will need to use -d flag
to indicate that initialization is required during the the approve
operation. Then you will need to initialize it with right initialization
parameters. Once you have these two things right, I think you should be ok.
Again, please read related docs on chaincode approval, chaincode
initialization and their relations.

Tong Li
IBM Open Technology



From:	Panagiotis Kirkinezis ***@***.***>
To:	hyperledger-labs/minifabric ***@***.***>
Cc:	litong01 ***@***.***>, Mention
            ***@***.***>
Date:	03/26/2021 12:57 PM
Subject:	[EXTERNAL] Re: [hyperledger-labs/minifabric] Error in ChainCode
            (Java Script) Installation (#172)



Thanks! @litong01 Folks! I'm stuck at initialize step. It's not moving
further. I checked all source code files of the smart contract. Basically,
I developed a smart contract in VS Code Extension of Fabric and trying to
deploy it here. I tried 


      Thanks! @litong01


      Folks!


      I'm stuck at initialize step. It's not moving further. I checked all
      source code files of the smart contract. Basically, I developed a
      smart contract in VS Code Extension of Fabric and trying to deploy it
      here. I tried tearing down and up the network again, as suggested by
      some people on stackexchange.


      Please suggest what went wrong.





Yeah . Its a common issue .
You have to check a few solutions .But first tell us
      What your init function is doing ?
      Does the ledger have any old data from previous version of
      chaincode ?


Because as @litong01 this indicates error in your init function and ferther
more maybe the key data your init functions tries to retrieve or set .

**Comment by RatakondalaArun** [comment]
@litong01 I am also having a similar issue
![image](https://user-images.githubusercontent.com/47482264/113288226-4ca98200-930c-11eb-92ac-942a7bfa2ce3.png)

My contract contains the name initLedger

when I try to invoke it shows this error

I used chain code from official fabric-samples https://github.com/hyperledger/fabric-samples/tree/main/chaincode/fabcar/javascript

**Comment by RatakondalaArun** [comment]
@litong01  But when I tried this chaincode [simple](https://github.com/hyperledger-labs/minifabric/tree/main/chaincode/simple) from this repo it works it uses low level `fabric-shim`

So how to use `fabric-contract-api`?

**Comment by litong01** [comment]
@RatakondalaArun please asking your question through fabric-mini channel. What you describe is not a minifabric issue. I am closing this due to no further activities about this.
