### ISSUE TITLE
Help: error with explorerup

### ISSUE THREAD

**Issue by zwnode** [hyperledger-labs/minifabric#192]
First, i run minifab up,it is ok. Then i run  minifab explorerup .It didn't report an error, but it  stays on this interface for a long time.
My env is linux ,ubuntu, and the container explorerdb.mysite is healthy.

![image](https://user-images.githubusercontent.com/75482436/115322873-8f4ad580-a1b9-11eb-8669-b3423876c168.png)

**Comment by litong01** [comment]
Can not recreate this issue. I suspect that your env was having issues. I am closing this now. If you still see the issue, please provide very detailed steps so that others can recreate this problem.

1. What OS were you using? OS version, Memory, CPU etc
2. How fabric was initially setup?
3. What version of Fabric were you trying to use?
4. Snapshot of your system resource
5. Docker version
