### ISSUE TITLE
Minifabric creates Admin userIds by default 

### ISSUE THREAD

**Issue by PuneetSivananda** [hyperledger-labs/minifabric#272]
This is more of like a feature query whether,  if it is already existing in minifabric, I see by default we are getting a admin user, is there documentation or feature requests where you can point me to see if i can create normal uses as well using the spec.yaml file, any help on this will be helpful 

Thanks

**Comment by litong01** [comment]
You can create your own certs and place in the right directories for nodes to use.

**Comment by PuneetSivananda** [comment]
Gotcha,  is there a documentation for creating user level certs I don't see them in the documentation, or might have missed them, could you point me to them or any resources would be helpful

**Comment by rafa977** [comment]
No, there is not a documentation for that in minifabric.

You can use the regular documentation of hyperledger fabric in order to create new users. I wanted also to create users in the network of minifabric and used the crypto-generator script and **fabric-ca-client** from hyperledger fabric ca. 

First I enrolled the admin that is already created in your network and then I registered new users pointing the output dir to your _vars/keyfiles/peerOrgs/org1/users_ folder.  
After registration I generated the user msp (Enrollment) using **fabric-ca-client** enroll.

Be aware that you can not use them with minifabric. You may use them with an sdk. In my case node. 

I hope that helps.

**Comment by PuneetSivananda** [comment]
Thanks @rafa977, Will try this method.
